### PR TITLE
dragonfly - Arbitrary Command Execution - Fix:

### PR DESCRIPTION
**Pull request by huntr-helper**
https://github.com/Asjidkalam fixed the vulnerability associated with Arbitrary Command Execution.
This fix is being submitted on behalf of https://github.com/Asjidkalam - they have been awarded $25 for fixing the vulnerability through the huntr bug bounty program.
Think you could fix a vulnerability like this - get involved (https://huntr.dev).
Q | A
Version Affected | ALL
Bug Fix | YES
Further References | https://github.com/418sec/dragonfly/pull/1

### CODE REVIEW

**Comment by JamieSlome** [comment]
@olly @dgiunta @zach - any updates on this?

**Comment by markevans** [comment]
hi what is this? If there's a vulnerability what are the details of it?

**Comment by JamieSlome** [comment]
Hello @markevans - correct this is a vulnerability.

@Asjidkalam, can you please provide more detail about your fix (if possible)? 🍰 

Cheers!

**Comment by Asjidkalam** [comment]
`OSVDB-97854`
Vulnerability details: https://snyk.io/vuln/SNYK-RUBY-DRAGONFLY-20016

Dragonfly Gem contains a flaw that is due to the program failing to properly escape a shell that contains injected characters. This may allow a context-dependent attacker to potentially execute arbitrary commands.

Mitigation:
[Terrapin libary](https://github.com/thoughtbot/terrapin) is used to properly escape the command, and no user injected command will be executed.
https://github.com/markevans/dragonfly/blob/40d98f057d3af9c2a841036433280e8f367649e7/lib/dragonfly/shell.rb#L23

@JamieSlome @markevans

**Comment by JamieSlome** [comment]
@Asjidkalam - awesome! 🍰

**Comment by markevans** [comment]
Thanks for this - though sorry I still need more details.
As you can imagine, I can't just introduce a new library dependency without understanding it and without any tests etc.

Are you sure there was still a vulnerability though?
That vulnerability seems to have been reported in 2011, for versions < 0.9.6 (we're now on 1.2.1 and a lot has changed since then https://github.com/markevans/dragonfly/blob/master/History.md ) There are checks for bad characters already e.g. https://github.com/markevans/dragonfly/blob/master/spec/dragonfly/shell_spec.rb#L26

**Comment by markevans** [comment]
closing due to inactivity - it seems to be addressing an old version which is already fixed

**Pull request closed without merging**
