### PR TITLE
Fix relative path when calling Dragonfly.app.store(tempfile, path: pa…

### PR DESCRIPTION
**Pull request by daareiza**
…th) method

### CODE REVIEW

**Comment by markevans** [comment]
hello - what's this needed for?

**Comment by daareiza** [comment]
Hello Mark,

when you call the method Dragonfly.app.store(tempfile, path: path), with the path argument, the filestore datastore does not recognize it, so it will always create his own path based on filename or 'file' string.

In my particular case, this is causing problems while storing temp files.

**Comment by daareiza** [comment]
Hello Mark, 

I am having the same issue with the s3 data store gem, its like the opts hash in the write method (def write(content, opts={}) always is empty.

**Comment by markevans** [comment]
`Dragonfly.app.store()` actually takes three arguments. the second is meta that's added to the content, and the third is the options that get passed to the store.

**Pull request closed without merging**
