### PR TITLE
add option for early convert arguments #391

### PR DESCRIPTION
**Pull request by trevvvy**
allows passing in imagemagick convert switches that will precede the
source file name.  useful for flags such as -density that must be set
before the source file in the convert command

Example:
`image.process(:convert, “100x100”, early_args: “-density 150”)`

### CODE REVIEW

**Comment by lcowell** [comment]
I've used this in one of my projects. Everything worked as expected.

**Comment by markevans** [comment]
hi - thanks for this. I'd prefer "input_args" - what do you reckon?

**Comment by trevvvy** [comment]
agreed. better name.

**Comment by lcowell** [comment]
travis is failing because it can't bundle `rubysl-openssl`. Does seem like anything related to this pull request.

**Comment by markevans** [comment]
cheers - merged in

**Pull request merged**
