### PR TITLE
Update magic attribute - Failing test

### PR DESCRIPTION
**Pull request by bobbus**
Story : add the possibility to modify the magic attribute `name` and use
it in the URL generated

Will this feature be interesting ? If there any way do to this in the actual version ?

Thanks for your help !

### CODE REVIEW

**Comment by markevans** [comment]
hi - is there a specific use case where this would be useful?

**Comment by bobbus** [comment]
@markevans : I want to use this in a SEO script to optimize image name

**Comment by markevans** [comment]
have you tried
    model.image.name = 'blah.png'
this will be used in the url and should set the magic attribute

**Comment by lcoq** [comment]
@bobbus +1

@markevans the same test fails when replacing `@item.preview_image_name = 'renamed.txt'` with `@item.preview_image.name = 'renamed.txt'`. Do I miss something ?

**Comment by lcoq** [comment]
@markevans is there any update on this issue ?

**Comment by markevans** [comment]
it does actually work (including just updating the magic attribute) if you reload the model.
In that particular test, as it's not using activerecord, this is done by replacing

    @item.preview_image.url

with

    @item_class.find(@item.id).preview_image.url

I'm not overly happy with the way this all works though. random thoughts out loud, which may or may not make any sense:
  - I could make sure `model.image.name = 'new.png'` correctly updates the url without needing to reload. However,  `name=` currently fetches the image from wherever it's stored, so it can update the meta that gets stored alongside the content, and I'm not sure if there's a better way that would avoid this.

**Pull request closed without merging**
